<a href="https://colab.research.google.com/github/mbrz97/ESP/blob/main/naft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import joblib
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
file_path = '/content/drive/MyDrive/datalast.joblib'

In [4]:
loaded_data = joblib.load(file_path)

In [5]:
import datetime
def remove_datetime_from_nested_list(nested_list):
    if isinstance(nested_list, list):
        return [remove_datetime_from_nested_list(item) for item in nested_list if not isinstance(item, datetime.datetime)]
    else:
        return nested_list

loaded_data = remove_datetime_from_nested_list(loaded_data)

In [6]:
x_data = [item[0] for item in loaded_data[0:5000]]
y_data = [item[1] for item in loaded_data[0:5000]]

In [7]:
# import numpy as np

# # Assuming ver_stack is your array
# contains_neg_inf = np.isneginf(x_data).any()

# if contains_neg_inf:
#     print("Input array contains negative infinity values.")
# else:
#     print("Input array does not contain negative infinity values.")


# contains_neg_inf = np.isneginf(y_data).any()

# if contains_neg_inf:
#     print("Input array contains negative infinity values.")
# else:
#     print("Input array does not contain negative infinity values.")

In [8]:
import numpy as np
x_data = np.array(x_data)
y_data = np.array(y_data)

In [9]:
del loaded_data

In [10]:
def convert_strings_to_floats(data):
    if isinstance(data, list):
        return [convert_strings_to_floats(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([convert_strings_to_floats(item) for item in data])
    elif isinstance(data, str):
        try:
            return float(data)
        except ValueError:
            return data
    else:
        return data


x_data = convert_strings_to_floats(x_data)
y_data = convert_strings_to_floats(y_data)

In [11]:
def remove_commas(data):
    if isinstance(data, list):
        return [remove_commas(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([remove_commas(item) for item in data])
    elif isinstance(data, str):
        return data.replace(',', '')
    else:
        return data

x_data = remove_commas(x_data)
y_data = remove_commas(y_data)

In [12]:
x_data.shape

(5000, 289, 8)

In [13]:
# # Iterate through the array and convert strings to floats
# for row in range(len(x_data)):
#     for col in range(len(x_data[row])):
#         element = x_data[row][col]
#         if isinstance(element, str):
#             # Remove commas and convert to float
#             x_data[row][col] = float(element.replace(",", ""))


# # Iterate through the array and convert strings to floats
# for row in range(len(y_data)):
#     for col in range(len(y_data[row])):
#         element = y_data[row][col]
#         if isinstance(element, str):
#             # Remove commas and convert to float
#             y_data[row][col] = float(element.replace(",", ""))

In [14]:
x_data.shape

(5000, 289, 8)

In [15]:
y_data.shape

(5000, 145, 8)

In [16]:
ver_stack = np.empty((0, 8))
j = 0
for i in range(0, len(x_data), 1000):
  for item in x_data[i]:
    j += 1
    #temp = train_set[i]
    print(100*100*j/(len(x_data)*289))
    ver_stack = np.vstack((ver_stack, item))

0.006920415224913495
0.01384083044982699
0.020761245674740483
0.02768166089965398
0.03460207612456748
0.04152249134948097
0.04844290657439446
0.05536332179930796
0.06228373702422145
0.06920415224913495
0.07612456747404844
0.08304498269896193
0.08996539792387544
0.09688581314878893
0.10380622837370242
0.11072664359861592
0.11764705882352941
0.1245674740484429
0.1314878892733564
0.1384083044982699
0.1453287197231834
0.1522491349480969
0.15916955017301038
0.16608996539792387
0.17301038062283736
0.17993079584775087
0.18685121107266436
0.19377162629757785
0.20069204152249134
0.20761245674740483
0.21453287197231835
0.22145328719723184
0.22837370242214533
0.23529411764705882
0.2422145328719723
0.2491349480968858
0.2560553633217993
0.2629757785467128
0.2698961937716263
0.2768166089965398
0.2837370242214533
0.2906574394463668
0.2975778546712803
0.3044982698961938
0.31141868512110726
0.31833910034602075
0.32525951557093424
0.33217993079584773
0.3391003460207612
0.3460207612456747
0.3529411764705

In [17]:
from sklearn.preprocessing import StandardScaler
myscaler = StandardScaler().fit(ver_stack)

In [18]:
for i in range(x_data.shape[0]):
  x_data[i] = myscaler.transform(x_data[i])

for j in range(y_data.shape[0]):
  print(y_data[j])
  y_data[j] = myscaler.transform(y_data[j])

Streaming output truncated to the last 5000 lines.
 [ 0.   0.   0.  ...  0.  30.2 20.8]
 [ 0.   0.   0.  ...  0.  24.6 20.8]]
[[ 0.   0.   0.  ...  0.  30.3 20.4]
 [ 0.   0.   0.  ...  0.  29.3 20.4]
 [ 0.   0.   0.  ...  0.  24.1 20.4]
 ...
 [ 0.   0.   0.  ...  0.  25.2 20.8]
 [ 0.   0.   0.  ...  0.  29.9 20.8]
 [ 0.   0.   0.  ...  0.  27.4 20.8]]
[[ 0.   0.   0.  ...  0.  24.  20.2]
 [ 0.   0.   0.  ...  0.  28.3 20.2]
 [ 0.   0.   0.  ...  0.  28.  20.2]
 ...
 [ 0.   0.   0.  ...  0.  27.2 20.7]
 [ 0.   0.   0.  ...  0.  30.2 20.7]
 [ 0.   0.   0.  ...  0.  28.9 20.7]]
[[ 0.   0.   0.  ...  0.  30.6 20.6]
 [ 0.   0.   0.  ...  0.  25.3 20.6]
 [ 0.   0.   0.  ...  0.  29.7 20.6]
 ...
 [ 0.   0.   0.  ...  0.  26.  20.7]
 [ 0.   0.   0.  ...  0.  25.3 20.7]
 [ 0.   0.   0.  ...  0.  24.4 20.7]]
[[ 0.   0.   0.  ...  0.  24.6 20.8]
 [ 0.   0.   0.  ...  0.  25.7 20.8]
 [ 0.   0.   0.  ...  0.  30.4 20.8]
 ...
 [ 0.   0.   0.  ...  0.  30.7 20.8]
 [ 0.   0.   0.  ...  0.  24.5 20.8]


In [19]:
y_data.shape

(5000, 145, 8)

In [20]:
train_num = round(len(x_data)*0.7)
val_num = round(len(x_data)*0.1)
test_num = round(len(x_data)*0.2)

x_train = x_data[0:train_num]
x_val = x_data[train_num:train_num + val_num]
x_test = x_data[train_num + val_num:]

train_num_y = round(len(y_data)*0.7)
val_num_y = round(len(y_data)*0.1)
test_num_y = round(len(y_data)*0.2)

y_train = y_data[0:train_num]
y_val = y_data[train_num:train_num + val_num]
y_test = y_data[train_num + val_num:]

In [21]:
ver_stack.shape

(1445, 8)

In [22]:
# def preprocess_function(x, scaler = scaler):
#   x_transformed = np.zeros_like(x)

#   for i in range(x.shape[0]):
#     # x[i] = scaler.fit_transform(x[i])
#     x_transformed[i] = scaler.fit_transform(x[i])
#     #print(x_transformed[i].shape)

#   return x_transformed

# def preprocess_function_batch(batch_x, scaler=scaler):
#     batch_size, seq_length, feature_dim = batch_x.shape
#     x_reshaped = batch_x.reshape(batch_size * seq_length, feature_dim)
#     x_transformed = scaler.fit_transform(x_reshaped)
#     x_transformed = x_transformed.reshape(batch_size, seq_length, feature_dim)
#     return x_transformed

In [23]:
from keras.utils import Sequence

class ESPDataGenerator(Sequence):
    def __init__(self, x_data, y_data, batch_size, shuffle=True, preprocess_function = None):
        self.x_data = x_data
        self.y_data = y_data
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indices = np.arange(len(self.x_data))
        self.preprocess_function = preprocess_function

        if self.shuffle:
            np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.x_data) / self.batch_size))

    def __getitem__(self, index):
        start_idx = index * self.batch_size
        end_idx = (index + 1) * self.batch_size
        batch_indices = self.indices[start_idx:end_idx]
        #print(self.x_data.shape)
        batch_x = self.x_data[batch_indices]
        #print(batch_x.shape)
        batch_y = self.y_data[batch_indices]

        if self.preprocess_function is not None:
          batch_x = self.preprocess_function(batch_x)
          batch_y = self.preprocess_function(batch_y)

        # You can add any preprocessing steps here
        #print(batch_x.shape)
        return batch_x, batch_y

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

batch_size = 16

data_generator = ESPDataGenerator(x_train, y_train, batch_size)
data_generator_val = ESPDataGenerator(x_val, y_val, batch_size)

epochs = 2

for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        # Train your model using the current batch
        pass

In [24]:
len(x_train[0])

289

In [25]:
# for epoch in range(epochs):
#     for batch_x, batch_y in data_generator:
#         print(batch_x)

In [26]:
# for x_batch, y_batch in data_generator:
#   print(x_batch)
#   print(x_batch.shape)

In [27]:
# loaded_data2[0]

In [ ]:
# for i in range(len(train_set)):
#   if len(train_set[i][0]) != 289:
#     print(len(train[i][0]))

In [ ]:
# len(loaded_data)

In [ ]:
# len(loaded_data[0][0])

In [ ]:
# import numpy as np

# shape = (len(loaded_data), len(loaded_data[0][0]), len(loaded_data[0][0][0]))
# data_array = np.zeros(shape)

# for i in range(len(loaded_data)):
#   data = loaded_data[i][0]

#   if len(data) != 289:
#     print(len(data))
#   #data_array[i] = data

In [ ]:

# def convert_to_numpy(obj):
#     if isinstance(obj, list):
#         return np.array([convert_to_numpy(item) for item in obj])
#     else:
#         return obj

# #converted_data = convert_to_numpy(loaded_data)

In [ ]:
#loaded_data = converted_data

In [ ]:
# import datetime

# def remove_datetime_objects(lst):
#     if isinstance(lst, list):
#         # Iterate through the list in reverse order to avoid index issues during removal
#         for i in range(len(lst) - 1, -1, -1):
#             if isinstance(lst[i], datetime.datetime):
#                 lst.pop(i)
#             else:
#                 remove_datetime_objects(lst[i])


# remove_datetime_objects(loaded_data)

In [ ]:
#loaded_data[0]

In [28]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
# train_num = round(len(loaded_data)*0.7)
# val_num = round(len(loaded_data)*0.1)
# test_num = round(len(loaded_data)*0.2)

# train_set = loaded_data[0:train_num]
# val_set = loaded_data[train_num:train_num + val_num]
# test_set = loaded_data[train_num + val_num:]

# #train_set = train_set

# # Split data into batches
# batch_size = train_num
# num_batches = train_num // batch_size
# num_features = 8

# # # Create an LSTM model
# # model = Sequential()
# # model.add(LSTM(units=64, activation='relu', input_shape=(len(loaded_data[0][0]), num_features)))
# # model.add(Dense(units=len(loaded_data[0][1]) * num_features))  # Output layer
# # model.compile(optimizer='adam', loss='mean_squared_error')

# # Define a custom data generator



In [ ]:
#train_set.ndim

In [ ]:
#converted_data = np.vectorize(lambda x: float(x.replace(',', '')))(ver_stack)


In [ ]:
# # Sample numpy array with empty arrays
# arr = np.array([[], [1, 2], [], [3, 4, 5], []])

# # Find indices of empty arrays
# empty_indices = np.where([len(sub_arr) == 0 for sub_arr in arr])[0]

# # Remove empty arrays
# arr = np.delete(arr, empty_indices, axis=0)

In [ ]:
# # Split data into batches
# batch_size = 32
# num_batches = len(train_set) // batch_size

# def data_generator(data_list, batch_size):
#     while True:
#         #for i in range(len(data_list)):
#         for batch in range(num_batches):
#             start_idx = batch * batch_size
#             end_idx = (batch + 1) * batch_size
#             batch_data = data_list[start_idx:end_idx]

#             x_batch = [inner[0] for inner in batch_data]
#             x_batch = scaler.fit_transform(x_batch)
#             x_batch = convert_to_numpy(x_batch)

#             y_batch = [inner[1] for inner in batch_data]
#             y_batch = scaler.fit_transform(y_batch)
#             y_batch = convert_to_numpy(y_batch)

#             yield x_batch, y_batch

In [ ]:
# def data_generator(data_list, batch_size):
#     #while True:
#   for i in range(len(data_list)):
#       x_batch = data_list[i][0]
#       #x_batch = scaler.fit_transform(x_batch)
#       x_batch = scaler.transform(x_batch)
#       x_batch = convert_to_numpy(x_batch)
#       x_batch = x_batch.reshape(1, len(data_list[i][0]), 8)
#       #empty_indices_x = np.where([len(sub_arr) == 0 for sub_arr in x_batch])[0]
#       #x_batch = np.delete(x_batch, empty_indices_x, axis
#       y_batch = data_list[i][1]
#       #y_batch = scaler.fit_transform(y_batch)
#       y_batch = scaler.transform(y_batch)
#       y_batch = convert_to_numpy(y_batch)
#       y_batch = y_batch.reshape(1, len(data_list[i][1]),8)
#       #empty_indices_y = np.where([len(sub_arr) == 0 for sub_arr in y_batch])[0]
#       #y_batch = np.delete(y_batch, empty_indices_y, axis

#       yield x_batch, y_batch

In [ ]:
# train_gen = data_generator(train_set, 1)
# val_gen = data_generator(val_set, 1)

In [ ]:
# x_train = [item[0] for item in train_set]
# y_train = [item[1] for item in train_set]

In [ ]:
# type(x_train)

In [ ]:

# len(x_train[0])

In [ ]:
# import numpy as np

# # Example nested list structure


# # Check shapes of sublists and sub-sublists
# shapes = set()
# for sublist in x_train:
#     for sub_sublist in sublist:
#         shapes.add(len(sub_sublist))
#         if len(sub_sublist) == 7:
#           print(sub_sublist)

# if len(shapes) > 1:
#     print("Sub-sublists have different lengths, cannot convert to NumPy array")
# else:
#     x_train = np.array(x_train)

# #print(x_train_array)


In [ ]:
# print(shapes)

In [29]:
x_train = np.array(x_train)
y_train = np.array(y_train)


In [44]:
x_train.shape

(3500, 289, 8)

In [30]:
x_train = x_train.reshape(len(x_train), len(x_train[0]),8)
y_train = y_train.reshape(len(y_train), len(y_train[0]),8)


In [ ]:
#len(x_train[0])

In [ ]:
#len(train_set[100][0])

In [ ]:
# for i in range(len(train_set)):
#   if len(x_train[i]) != 289:
#     print("X mismatch: ", len(train_set[i]), i)
#   elif len(y_train[i]) != 145:
#     print("Y mismatch: ", len(train_set[i]), i)


In [ ]:
#len(val_set)

In [ ]:
#aa = next(train_gen)

In [ ]:
#type(aa[0])

In [ ]:
#aa[0].shape

In [ ]:
# g = data_generator(train_set, 1)
# for value in g:
#   if value[0].shape != (1, 289, 8):
#     print(value[0].shape)
#   if value[1].shape != (1, 145, 8):
#     print(value[1].shape)

In [ ]:
  # x_train = [sublist[0] for sublist in train_set]
  # x_val = [sublist[0] for sublist in val_set]

In [ ]:
# y_train = [sublist[1] for sublist in train_set]
# y_val = [sublist[1] for sublist in val_set]

In [ ]:
#type(x_train[0])

In [ ]:
# def convert_to_numpy(data):
#     if isinstance(data, list):
#         return np.array([convert_to_numpy(item) for item in data])
#     else:
#         return data

# y_val = convert_to_numpy(y_val)

In [ ]:
#type(y_val[0])

In [31]:
# multivariate multi-step encoder-decoder lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

In [ ]:
#x_train.ndim

In [ ]:
# x_sample, y_sample = next(train_gen)
# type(y_sample)

In [ ]:
#x_sample

In [ ]:
#x_train[0]

In [ ]:
# # x_train = scaler.fit_transform(x_train)
# # y_train = scaler.fit_transform(y_train)

# # TODO

# # Assuming x_train and y_train have shapes (num_samples, num_time_steps, num_features)
# # Reshape to (num_samples * num_time_steps, num_features)
# x_train = x_train.reshape(-1, num_features)
# y_train = y_train.reshape(-1, num_features)

# # Initialize the StandardScaler

# # Fit and transform the scaler on the reshaped data
# x_train = scaler.fit_transform(x_train)
# y_train = scaler.fit_transform(y_train)

# # Reshape the scaled data back to their original shapes if needed
# x_train = x_train.reshape(1, 288, num_features)
# y_train = y_train.reshape(1, 144, num_features)


In [32]:
import numpy as np
from keras.callbacks import Callback

class NMSECallback(Callback):
    def __init__(self, x_val, y_val):
        self.x_val = x_val
        self.y_val = y_val

    def on_epoch_end(self, epoch, logs=None):
        predictions = self.model.predict(self.x_val)
        mse = np.sqrt(np.mean(np.square(predictions - self.y_val)))
        true_variance = np.sqrt(np.var(self.y_val))
        nmse = mse / true_variance
        print(f'\nEpoch {epoch + 1} - NMSE: {nmse:.4f}')

# Create the NMSE callback
nmse_callback = NMSECallback(x_val, y_val)

In [33]:
# Build the LSTM model
from keras.models import Sequential
from keras.layers import LSTM, Dense, RepeatVector, TimeDistributed
from tensorflow.keras.layers import Reshape
from keras.optimizers import Adam

#lr = 0.1  # Adjust this value as needed
#optimizer = Adam(learning_rate=lr)

model = Sequential()
#model.add(Reshape((num_features, 1), input_shape=(num_features,)))
#model.add(LSTM(50, input_shape=(len(train_set[0][0]), num_features), activation='relu'))
model.add(LSTM(50, activation='tanh'))
model.add(RepeatVector(145))
model.add(LSTM(50, return_sequences=True, activation='tanh'))
model.add(TimeDistributed(Dense(8)))  # Predict all 8 features for each step in the sequence
model.compile(optimizer='adam', loss='mse')


# Train the model
#history = model.fit(train_gen, epochs=1, validation_data=val_gen)
history = model.fit(data_generator, epochs=1, batch_size=16, validation_data=(x_val, y_val), callbacks=[nmse_callback])

16/16 [==============================] - 2s 58ms/step

Epoch 1 - NMSE: 0.1557
219/219 [==============================] - 64s 268ms/step - loss: 0.0812 - val_loss: 0.0224


In [34]:
print(history.history['val_loss'])

[0.022410999983549118]


In [35]:
from sklearn.metrics import mean_squared_error

def calculate_nmse(y_true, y_pred):
    mse = np.sqrt(np.mean(np.square(y_pred - y_true)))
    true_variance = np.sqrt(np.var(y_true))
    nmse = mse / true_variance
    return mse, nmse

# Evaluate the model and calculate NMSE
predictions = model.predict(x_test)
mse, nmse = calculate_nmse(y_test, predictions)

print("Normalized Mean Squared Error on Test Data:", nmse)
print("Mean Squared Error on Test Data:", mse, nmse)

32/32 [==============================] - 2s 74ms/step
Normalized Mean Squared Error on Test Data: 0.12465569967735561
Mean Squared Error on Test Data: 0.15926558764497117 0.12465569967735561


In [36]:
from sklearn.metrics import mean_absolute_error

# Reshape y_test and predictions
num_samples, num_steps, num_features = y_test.shape
y_test_reshaped = y_test.reshape(num_samples * num_steps, num_features)
predictions_reshaped = predictions.reshape(num_samples * num_steps, num_features)

# Calculate Mean Absolute Error
mae = mean_absolute_error(y_test_reshaped, predictions_reshaped)
print("Mean Absolute Error on Test Data:", mae)


Mean Absolute Error on Test Data: 0.06747882560032456


In [37]:
# Now, we want to figure out: From our failure data, which ones are actually failure

file_path_fail = '/content/drive/MyDrive/new_failure.joblib'
failure_data = joblib.load(file_path_fail)

In [38]:
# Remove Datetime (index 0) and Time to Failure (index -1)

for key, value in failure_data.items():
    for sublist in value:
        if len(sublist) >= 2:
            sublist.pop(0)   # Remove the 0th index
            sublist.pop(-1)  # Remove the last index

In [39]:
for key, value in failure_data.items():
    for sublist in value:
      if len(sublist) > 8:
        sublist.pop(-1)
      print(sublist)


Streaming output truncated to the last 5000 lines.
['341.10', '0.00', '88.0', '100.9', '0.599', '0.163', '121.3', '9.7']
['341.60', '0.00', '87.9', '100.9', '0.647', '0.160', '121.3', '9.7']
['340.10', '0.00', '87.9', '101.0', '0.540', '0.187', '121.0', '9.7']
['341.50', '0.00', '87.9', '100.9', '0.600', '0.205', '121.4', '9.7']
['342.10', '0.00', '87.9', '100.9', '0.484', '0.169', '121.3', '9.7']
['339.70', '0.00', '87.9', '100.9', '0.526', '0.193', '121.4', '9.7']
['340.90', '0.00', '87.9', '100.9', '0.549', '0.134', '121.2', '9.7']
['340.90', '0.00', '87.9', '100.9', '0.593', '0.225', '121.3', '9.7']
['341.80', '0.00', '87.9', '100.9', '0.596', '0.168', '121.3', '9.7']
['342.70', '0.00', '87.9', '101.1', '0.558', '0.163', '121.4', '9.7']
['340.20', '0.00', '87.9', '101.1', '0.452', '0.225', '121.3', '9.7']
['339.20', '0.00', '87.9', '101.1', '0.546', '0.208', '121.4', '9.7']
['340.20', '0.00', '87.9', '100.9', '0.584', '0.169', '121.0', '9.7']
['343.40', '0.00', '87.9', '101.2', '0.

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
[458.6, 0, 89.1, 103, 0.374, 0.15, 121.4, 9.7]
[459.7, 0, 89.1, 102.5, 0.352, 0.178, 121.3, 9.7]
[459.8, 0, 89.1, 102.4, 0.428, 0.163, 121.3, 9.7]
[458.8, 0, 89.1, 102.3, 0.334, 0.166, 121.4, 9.7]
[456.3, 0, 89.1, 102.4, 0.386, 0.171, 121, 9.7]
[456.3, 0, 89.1, 102.3, 0.431, 0.172, 121.4, 9.7]
[455.6, 0, 89.1, 102.3, 0.399, 0.154, 121.2, 9.7]
[455.7, 0, 89.1, 102.3, 0.372, 0.128, 121.3, 9.7]
[453.2, 0, 89.1, 102.3, 0.387, 0.169, 121.3, 9.7]
[452.3, 0, 89.1, 102.3, 0.369, 0.157, 121, 9.7]
[453.9, 0, 89.1, 102.3, 0.405, 0.21, 121.4, 9.7]
[453.5, 0, 89.1, 102.3, 0.476, 0.14, 121, 9.7]
[454, 0, 89.1, 102.3, 0.541, 0.148, 121.3, 9.7]
[454.5, 0, 89.1, 102.3, 0.497, 0.157, 121.3, 9.7]
[454.7, 0, 89.1, 102.4, 0.393, 0.174, 121.3, 9.7]
[455.3, 0, 89.1, 103, 0.482, 0.131, 121.4, 9.7]
[457.2, 0, 89.1, 102.5, 0.288, 0.145, 121, 9.7]
[456.7, 0, 89.1, 102.3, 0.405, 0.134, 121, 9.7]
[456.3, 0, 89.1, 102.3, 0.316, 0.166, 121.2, 9.7]
[455.5, 0, 89.1, 1

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
['988.9', '5,799.9', '112.1', '114.9', '0.585', '0.127', '120.7', '9.9']
['988.2', '5,801.2', '112.1', '114.8', '0.475', '0.125', '120.9', '9.9']
['988.7', '5,800.6', '112.1', '114.9', '0.525', '0.116', '120.3', '9.9']
['988.8', '5,801.3', '112.1', '114.9', '0.602', '0.14', '120.4', '9.9']
['988.4', '5,800.7', '112.1', '114.9', '0.469', '0.104', '120.4', '9.9']
['988.8', '5,800', '112.1', '114.9', '0.567', '0.144', '120.9', '9.9']
['989', '5,800.7', '112.1', '114.8', '0.629', '0.113', '120.9', '9.9']
['989.5', '5,800.8', '112.1', '114.8', '0.565', '0.128', '120.9', '9.9']
['988.7', '5,801', '112.1', '114.9', '0.599', '0.107', '120.5', '9.9']
['988.9', '5,801.5', '112.1', '114.8', '0.688', '0.131', '120.5', '9.9']
['988.5', '5,801.5', '112.1', '114.8', '0.552', '0.134', '120.4', '9.9']
['988.9', '5,801.3', '112.1', '114.8', '0.552', '0.145', '120.7', '9.9']
['988.9', '5,799.9', '112.1', '114.9', '0.528', '0.139', '120.3', '9.9']
['989.2

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
[112.55, 79.7, 82.8, 120, 0.956, 0.394, 122.2, 11.2]
[112.57, 79.67, 82.7, 120, 1.038, 0.391, 122.2, 11.2]
[112.57, 79.65, 82.8, 120.1, 0.821, 0.372, 117.6, 11.2]
[112.58, 79.62, 82.8, 120, 1.105, 0.404, 121.4, 11.2]
[112.51, 79.73, 82.8, 119.9, 0.951, 0.478, 121.4, 11.2]
[112.58, 79.77, 82.7, 120, 0.951, 0.37, 121.7, 11.2]
[112.6, 79.72, 82.7, 119.9, 1.086, 0.348, 121.4, 11.2]
[112.59, 79.65, 82.7, 120, 1.027, 0.409, 122.3, 11.2]
[112.55, 79.68, 82.7, 120, 1.078, 0.409, 121.3, 11.2]
[112.54, 79.72, 82.8, 120, 1.006, 0.4, 121.4, 11.2]
[112.56, 79.65, 82.8, 120.1, 0.709, 0.367, 121.4, 11.2]
[112.52, 79.81, 82.8, 120, 0.596, 0.425, 121.4, 11.2]
[112.55, 79.69, 82.7, 120, 1.164, 0.442, 122, 11.2]
[112.55, 79.68, 82.8, 120.1, 0.548, 0.419, 121.3, 11.2]
[112.55, 79.54, 82.7, 120, 0.958, 0.417, 122.2, 11.2]
[112.55, 79.74, 82.8, 120, 0.915, 0.401, 121.3, 11.2]
[112.59, 79.72, 82.7, 120, 0.723, 0.378, 121.5, 11.2]
[112.54, 79.77, 82.7, 120, 0

In [40]:
failure_data['a-2']

[[673.8, 5801.5, 104, 121.1, 0.776, 0.142, 120.9, 9.8],
 [676.1, 5801.5, 104, 121.3, 0.681, 0.164, 121, 9.8],
 [673.1, 5801.5, 104, 121.3, 0.934, 0.188, 121.3, 9.8],
 [669.6, 5801.5, 104, 121.3, 0.836, 0.161, 120.7, 9.8],
 [671.1, 5801.5, 104, 121.3, 1.019, 0.152, 121.2, 9.8],
 [667, 5801.5, 104, 121.3, 0.893, 0.164, 121, 9.8],
 [670.4, 5801.5, 104, 121.4, 0.923, 0.129, 120.9, 9.8],
 [668.5, 5801.5, 104, 121.3, 0.792, 0.171, 121, 9.8],
 [674.1, 5801.5, 104, 121.3, 0.937, 0.141, 121.3, 9.8],
 [671.4, 5801.5, 104, 121.2, 0.692, 0.127, 120.8, 9.8],
 [674.7, 5801.5, 104, 121.4, 0.804, 0.166, 120.7, 9.8],
 [673.2, 5801.5, 104, 121.4, 0.793, 0.147, 120.7, 9.8],
 [667, 5801.5, 104, 121.3, 0.827, 0.159, 120.9, 9.8],
 [670.3, 5801.5, 104, 121.4, 1.028, 0.153, 121, 9.8],
 [665.7, 5801.5, 104, 121.2, 1.109, 0.142, 120.7, 9.8],
 [667.5, 5801.5, 104, 121.3, 0.842, 0.146, 121.2, 9.8],
 [668.9, 5801.4, 104, 121.3, 1.004, 0.141, 121.4, 9.8],
 [673.5, 5801.5, 104, 121.4, 0.742, 0.173, 120.7, 9.8],
 [67

In [41]:

for key, value in failure_data.items():
    for i in range(len(value)):
        for j in range(len(value[i])):
            if isinstance(value[i][j], str):
                # Remove commas if present
                value[i][j] = value[i][j].replace(',', '')

                try:
                    # Convert to float if it's a string
                    value[i][j] = float(value[i][j])
                except ValueError:
                    # Handle if conversion to float fails
                    pass


In [47]:
failure_data['a-2'][0]

array([ 0.28619062,  0.60245745,  0.58332738,  0.69945701,  1.39559384,
       -0.48850929,  0.47066565, -0.51452308])

In [43]:


for key, value in failure_data.items():
  temp_val = value
  temp_val = myscaler.transform(temp_val)
  failure_data[key] = temp_val
  del temp_val


TODO:

make_window, take first 188 readings, next 145 for labels

loop over

take index that loss is great

In [92]:
failure_window = {}

for key, value in failure_data.items():
  my_list = []
  stride = 0
  for i in range(len(value)):
    stride += 36
    if len(value) > 440 and (stride+289+145) < len(value):
      feature = value[stride: stride+289]
      label = value[stride+289:stride+289+145]
      my_list.append([feature, label])
      failure_window[key] = my_list

In [75]:
failure_window[key][0]

[array([[ 0.28619062,  0.60245745,  0.58332738, ..., -0.48449004,
          0.47066565, -0.51452308],
        [ 0.28673491,  0.60245745,  0.58332738, ..., -0.40008591,
          0.47066565, -0.51452308],
        [ 0.2853742 ,  0.60245745,  0.58332738, ..., -0.48449004,
          0.47330334, -0.51452308],
        ...,
        [ 0.2674128 ,  0.60245745,  0.58332738, ..., -0.2915663 ,
          0.47857872, -0.51452308],
        [ 0.27884278,  0.60245745,  0.58332738, ..., -0.27548932,
          0.4812164 , -0.51452308],
        [ 0.27938706,  0.60245745,  0.58332738, ..., -0.32372026,
          0.46802797, -0.51452308]]),
 array([[ 0.29381061,  0.60245745,  0.58332738, ..., -0.52468249,
          0.4812164 , -0.51452308],
        [ 0.28619062,  0.60245745,  0.58332738, ..., -0.35185497,
          0.4812164 , -0.51452308],
        [ 0.29598775,  0.60245745,  0.58332738, ..., -0.35185497,
          0.46802797, -0.51452308],
        ...,
        [ 0.26441923,  0.60245745,  0.58332738, ..., -

In [94]:
failure_window['a-2'][2][0].shape

(289, 8)

In [93]:
for key, value in failure_window.items():
  for meh in range(len(value)):
    if failure_window[key][meh][0].shape != (289, 8) or failure_window[key][meh][1].shape != (145, 8):
      print(failure_window[key][meh][0].shape, failure_window[key][meh][1].shape)

In [ ]:
  # print(type(x_train), x_train.shape)
  # print(type(y_train), y_train.shape)


In [ ]:
# if np.isnan(x_train).any() or np.isnan(y_train).any():
#     print("There are NaN values in the dataset.")

# if np.isinf(x_train).any() or np.isinf(y_train).any():
#     print("There are Inf values in the dataset.")

TypeError: ignored

In [ ]:
# x_train.shape

(15091, 289, 8)

In [ ]:
# y_train.shape

(15091, 145, 8)

In [ ]:
file_path2 = '/content/drive/MyDrive/datafailure.joblib'
loaded_data2 = joblib.load(file_path2)
loaded_data2 = remove_datetime_from_nested_list(loaded_data2)
x_data2 = [item[0] for item in loaded_data2[0:5000]]
y_data2 = [item[1] for item in loaded_data2[0:5000]]
x_data2 = np.array(x_data2)
y_data2 = np.array(y_data2)
del loaded_data2

x_data2 = convert_strings_to_floats(x_data2)
y_data2 = convert_strings_to_floats(y_data2)

x_data2 = remove_commas(x_data2)
y_data2 = remove_commas(y_data2)


# Iterate through the array and convert strings to floats
for row in range(len(x_data2)):
    for col in range(len(x_data2[row])):
        element = x_data2[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            x_data2[row][col] = float(element.replace(",", ""))


# Iterate through the array and convert strings to floats
for row in range(len(y_data2)):
    for col in range(len(y_data2[row])):
        element = y_data2[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            y_data2[row][col] = float(element.replace(",", ""))


for i in range(x_data2.shape[0]):
  x_data2[i] = myscaler.transform(x_data2[i])

for j in range(y_data.shape[0]):
  print(y_data2[j])
  y_data2[j] = myscaler.transform(y_data2[j])

In [ ]:
predictions2 = model.predict(x_data2)
nmse2 = calculate_nmse(y_data2, predictions2)

print("Normalized Mean Squared Error on Failure Test Data:", nmse2)

157/157 [==============================] - 11s 71ms/step
Normalized Mean Squared Error on Failure Test Data: 0.42346157914366256


In [ ]:
# __________________________________

In [ ]:
file_path3 = '/content/drive/MyDrive/failure_all.joblib'
loaded_data3 = joblib.load(file_path3)

In [ ]:
import datetime
def remove_datetime_from_nested_list(nested_list):
    if isinstance(nested_list, list):
        return [remove_datetime_from_nested_list(item) for item in nested_list if not isinstance(item, datetime.datetime)]
    else:
        return nested_list

loaded_data3 = remove_datetime_from_nested_list(loaded_data3)

In [ ]:
data3 = []
for key, value in loaded_data3.items():
  data3.append(value)

In [ ]:
import numpy as np
x_data3 = [[subsublist[1:9] for subsublist in sublist] for sublist in data3]
y_data3 = [[subsublist[-1] for subsublist in sublist] for sublist in data3]

def remove_commas(data):
    if isinstance(data, list):
        return [remove_commas(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([remove_commas(item) for item in data])
    elif isinstance(data, str):
        return data.replace(',', '')
    else:
        return data


def convert_strings_to_floats(data):
    if isinstance(data, list):
        return [convert_strings_to_floats(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([convert_strings_to_floats(item) for item in data])
    elif isinstance(data, str):
        try:
            return float(data)
        except ValueError:
            return data
    else:
        return data


x_data3 = remove_commas(x_data3)
x_data3 = convert_strings_to_floats(x_data3)


x_data3 = np.array(x_data3)
y_data3 = np.array(y_data3)
# del loaded_data3

<ipython-input-21-29e850c9e99a>:34: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_data3 = np.array(x_data3)
<ipython-input-21-29e850c9e99a>:35: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y_data3 = np.array(y_data3)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import numpy as np

# Use pad_sequences with dtype='float32' to pad your sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences




In [ ]:
x_data3.shape

(26,)

In [ ]:

# # Find the maximum sequence length
# max_sequence_length = max(len(sequence) for sequence in x_data3)

# # Find the number of features per timestep (assuming all timesteps have the same number of features)
# num_features = len(x_data3[0][0])

# # Create a new NumPy array for the padded sequences
# X_padded = np.zeros((len(x_data3), max_sequence_length, num_features), dtype='float32')



# # Copy each sequence into the new array
# for i, sequence in enumerate(x_data3):
#     X_padded[i, :len(sequence), :] = sequence


x_data3 = [np.array(sequence) for sequence in x_data3]

# Find the maximum sequence length
max_sequence_length = max(len(sequence) for sequence in x_data3)

# Find the number of features per timestep
num_features = x_data3[0].shape[1]

# Create a new NumPy array for the padded sequences
X_padded = np.zeros((len(x_data3), max_sequence_length, num_features))

# Copy each sequence into the new array
for i, sequence in enumerate(x_data3):
    X_padded[i, :len(sequence), :] = sequence



# =========================================================

# Convert each individual sequence in y to a NumPy array
y = [np.array(sequence) for sequence in y_data3]

# Find the maximum sequence length in y
max_sequence_length_y = max(len(sequence) for sequence in y)

# Create a new NumPy array for the padded sequences in y
y_padded = np.zeros((len(y), max_sequence_length_y, 1))  # Assuming y contains 1 feature per timestep

# Copy each sequence into the new array
for i, sequence in enumerate(y):
    y_padded[i, :len(sequence), 0] = sequence  # Assuming y contains 1D sequences


for i in range(X_padded.shape[0]):
  X_padded[i] = myscaler.transform(X_padded[i])



X_train, X_test, y_train, y_test = train_test_split(X_padded, y_padded, test_size=0.2, random_state=42)


In [ ]:
X_padded.shape

(26, 122503, 8)

In [ ]:
y_padded.shape

(26, 122503, 1)

In [ ]:
from keras.utils import Sequence

class ESPDataGenerator(Sequence):
    def __init__(self, x_data, y_data, batch_size, shuffle=False, preprocess_function = None):
        self.x_data = x_data
        self.y_data = y_data
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indices = np.arange(len(self.x_data))
        self.preprocess_function = preprocess_function

        if self.shuffle:
            np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.x_data) / self.batch_size))

    def __getitem__(self, index):
        start_idx = index * self.batch_size
        end_idx = (index + 1) * self.batch_size
        batch_indices = self.indices[start_idx:end_idx]
        #print(self.x_data.shape)
        batch_x = self.x_data[batch_indices]
        #print(batch_x.shape)
        batch_y = self.y_data[batch_indices]

        if self.preprocess_function is not None:
          batch_x = self.preprocess_function(batch_x)
          batch_y = self.preprocess_function(batch_y)

        # You can add any preprocessing steps here
        #print(batch_x.shape)
        return batch_x, batch_y

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

batch_size = 1

data_generator = ESPDataGenerator(X_train, y_train, batch_size)
#data_generator_val = ESPDataGenerator(x_val, y_val, batch_size)

epochs = 1

for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        # Train your model using the current batch
        pass

In [ ]:
X_train[0]

array([[ 2.81357732,  0.60245745,  0.50916385, ...,  0.4278785 ,
         0.44165109, -0.51452308],
       [ 2.81276089,  0.60245745,  0.50916385, ...,  0.74137958,
         0.43373803, -0.51452308],
       [ 2.81303304,  0.60245745,  0.50916385, ...,  0.80166825,
         0.42846266, -0.51452308],
       ...,
       [-1.54750503, -1.69779501, -1.98767498, ..., -1.05924203,
        -2.71829841, -2.79729809],
       [-1.54750503, -1.69779501, -1.98767498, ..., -1.05924203,
        -2.71829841, -2.79729809],
       [-1.54750503, -1.69779501, -1.98767498, ..., -1.05924203,
        -2.71829841, -2.79729809]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, TimeDistributed, Masking
from tensorflow.keras.optimizers import Adam

# Define your desired learning rate (e.g., 0.001)
learning_rate = 0.001

# Create an Adam optimizer with the desired learning rate
custom_optimizer = Adam(learning_rate=learning_rate)

# Build your model
model = Sequential([
    Masking(mask_value=0.0, input_shape=(X_train.shape[1], X_train.shape[2])),
    LSTM(1, activation='tanh', return_sequences=True),
    TimeDistributed(Dense(1, activation='linear'))
])

# Compile the model using the custom optimizer and specified loss
model.compile(optimizer=custom_optimizer, loss='mse')


history = model.fit(X_train, y_train, epochs=1, batch_size=1, validation_data=(X_test, y_test))

20/20 [==============================] - 5472s 273s/step - loss: 21036566.0000 - val_loss: 3031020.0000


In [ ]:
model.save("model.h5")

In [ ]:
X_test.shape

(6, 122503, 8)

In [ ]:
from sklearn.metrics import r2_score
import numpy as np

# Assuming you have trained your model and have predictions for X_test
predictions = model.predict(X_test)

# Reshape predictions and y_test to match for R2 score calculation
predictions = predictions.reshape(-1, 1)  # Reshape to (735018, 1)

# Flatten y_test and reshape
y_test = y_test.flatten()  # Flatten to (735018,)

# Calculate R2 score
r2 = r2_score(y_test, predictions)

print("R-squared (R2) score:", r2)


1/1 [==============================] - 15s 15s/step
R-squared (R2) score: -0.16750900651076428


In [ ]:
for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        print(batch_x)