<a href="https://colab.research.google.com/github/mbrz97/ESP/blob/main/naft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import joblib
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
file_path = '/content/drive/MyDrive/datalast.joblib'

In [4]:
loaded_data = joblib.load(file_path)

In [5]:
import datetime
def remove_datetime_from_nested_list(nested_list):
    if isinstance(nested_list, list):
        return [remove_datetime_from_nested_list(item) for item in nested_list if not isinstance(item, datetime.datetime)]
    else:
        return nested_list

loaded_data = remove_datetime_from_nested_list(loaded_data)

In [6]:
x_data = [item[0] for item in loaded_data[0:5000]]
y_data = [item[1] for item in loaded_data[0:5000]]

In [8]:
# import numpy as np

# # Assuming ver_stack is your array
# contains_neg_inf = np.isneginf(x_data).any()

# if contains_neg_inf:
#     print("Input array contains negative infinity values.")
# else:
#     print("Input array does not contain negative infinity values.")


# contains_neg_inf = np.isneginf(y_data).any()

# if contains_neg_inf:
#     print("Input array contains negative infinity values.")
# else:
#     print("Input array does not contain negative infinity values.")

TypeError: ignored

In [9]:
import numpy as np
x_data = np.array(x_data)
y_data = np.array(y_data)

In [10]:
del loaded_data

In [11]:
def convert_strings_to_floats(data):
    if isinstance(data, list):
        return [convert_strings_to_floats(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([convert_strings_to_floats(item) for item in data])
    elif isinstance(data, str):
        try:
            return float(data)
        except ValueError:
            return data
    else:
        return data


x_data = convert_strings_to_floats(x_data)
y_data = convert_strings_to_floats(y_data)

In [12]:
def remove_commas(data):
    if isinstance(data, list):
        return [remove_commas(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([remove_commas(item) for item in data])
    elif isinstance(data, str):
        return data.replace(',', '')
    else:
        return data

x_data = remove_commas(x_data)
y_data = remove_commas(y_data)

In [13]:
x_data.shape[0]

5000

In [14]:
# Iterate through the array and convert strings to floats
for row in range(len(x_data)):
    for col in range(len(x_data[row])):
        element = x_data[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            x_data[row][col] = float(element.replace(",", ""))


# Iterate through the array and convert strings to floats
for row in range(len(y_data)):
    for col in range(len(y_data[row])):
        element = y_data[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            y_data[row][col] = float(element.replace(",", ""))

In [15]:
x_data.shape


(5000, 289, 8)

In [16]:
y_data.shape

(5000, 145, 8)

In [17]:
ver_stack = np.empty((0, 8))
j = 0
for i in range(0, len(x_data), 1000):
  for item in x_data[i]:
    j += 1
    #temp = train_set[i]
    print(100*100*j/(len(x_data)*289))
    ver_stack = np.vstack((ver_stack, item))

0.006920415224913495
0.01384083044982699
0.020761245674740483
0.02768166089965398
0.03460207612456748
0.04152249134948097
0.04844290657439446
0.05536332179930796
0.06228373702422145
0.06920415224913495
0.07612456747404844
0.08304498269896193
0.08996539792387544
0.09688581314878893
0.10380622837370242
0.11072664359861592
0.11764705882352941
0.1245674740484429
0.1314878892733564
0.1384083044982699
0.1453287197231834
0.1522491349480969
0.15916955017301038
0.16608996539792387
0.17301038062283736
0.17993079584775087
0.18685121107266436
0.19377162629757785
0.20069204152249134
0.20761245674740483
0.21453287197231835
0.22145328719723184
0.22837370242214533
0.23529411764705882
0.2422145328719723
0.2491349480968858
0.2560553633217993
0.2629757785467128
0.2698961937716263
0.2768166089965398
0.2837370242214533
0.2906574394463668
0.2975778546712803
0.3044982698961938
0.31141868512110726
0.31833910034602075
0.32525951557093424
0.33217993079584773
0.3391003460207612
0.3460207612456747
0.3529411764705

In [18]:
from sklearn.preprocessing import StandardScaler
myscaler = StandardScaler().fit(ver_stack)

In [19]:
for i in range(x_data.shape[0]):
  x_data[i] = myscaler.transform(x_data[i])

for j in range(y_data.shape[0]):
  print(y_data[j])
  y_data[j] = myscaler.transform(y_data[j])

Streaming output truncated to the last 5000 lines.
 [ 0.   0.   0.  ...  0.  30.2 20.8]
 [ 0.   0.   0.  ...  0.  24.6 20.8]]
[[ 0.   0.   0.  ...  0.  30.3 20.4]
 [ 0.   0.   0.  ...  0.  29.3 20.4]
 [ 0.   0.   0.  ...  0.  24.1 20.4]
 ...
 [ 0.   0.   0.  ...  0.  25.2 20.8]
 [ 0.   0.   0.  ...  0.  29.9 20.8]
 [ 0.   0.   0.  ...  0.  27.4 20.8]]
[[ 0.   0.   0.  ...  0.  24.  20.2]
 [ 0.   0.   0.  ...  0.  28.3 20.2]
 [ 0.   0.   0.  ...  0.  28.  20.2]
 ...
 [ 0.   0.   0.  ...  0.  27.2 20.7]
 [ 0.   0.   0.  ...  0.  30.2 20.7]
 [ 0.   0.   0.  ...  0.  28.9 20.7]]
[[ 0.   0.   0.  ...  0.  30.6 20.6]
 [ 0.   0.   0.  ...  0.  25.3 20.6]
 [ 0.   0.   0.  ...  0.  29.7 20.6]
 ...
 [ 0.   0.   0.  ...  0.  26.  20.7]
 [ 0.   0.   0.  ...  0.  25.3 20.7]
 [ 0.   0.   0.  ...  0.  24.4 20.7]]
[[ 0.   0.   0.  ...  0.  24.6 20.8]
 [ 0.   0.   0.  ...  0.  25.7 20.8]
 [ 0.   0.   0.  ...  0.  30.4 20.8]
 ...
 [ 0.   0.   0.  ...  0.  30.7 20.8]
 [ 0.   0.   0.  ...  0.  24.5 20.8]


In [20]:
y_data.shape

(5000, 145, 8)

In [21]:
train_num = round(len(x_data)*0.7)
val_num = round(len(x_data)*0.1)
test_num = round(len(x_data)*0.2)

x_train = x_data[0:train_num]
x_val = x_data[train_num:train_num + val_num]
x_test = x_data[train_num + val_num:]

train_num_y = round(len(y_data)*0.7)
val_num_y = round(len(y_data)*0.1)
test_num_y = round(len(y_data)*0.2)

y_train = y_data[0:train_num]
y_val = y_data[train_num:train_num + val_num]
y_test = y_data[train_num + val_num:]

In [22]:
ver_stack.shape

(1445, 8)

In [23]:
# def preprocess_function(x, scaler = scaler):
#   x_transformed = np.zeros_like(x)

#   for i in range(x.shape[0]):
#     # x[i] = scaler.fit_transform(x[i])
#     x_transformed[i] = scaler.fit_transform(x[i])
#     #print(x_transformed[i].shape)

#   return x_transformed

# def preprocess_function_batch(batch_x, scaler=scaler):
#     batch_size, seq_length, feature_dim = batch_x.shape
#     x_reshaped = batch_x.reshape(batch_size * seq_length, feature_dim)
#     x_transformed = scaler.fit_transform(x_reshaped)
#     x_transformed = x_transformed.reshape(batch_size, seq_length, feature_dim)
#     return x_transformed

NameError: ignored

In [24]:
from keras.utils import Sequence

class ESPDataGenerator(Sequence):
    def __init__(self, x_data, y_data, batch_size, shuffle=True, preprocess_function = None):
        self.x_data = x_data
        self.y_data = y_data
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indices = np.arange(len(self.x_data))
        self.preprocess_function = preprocess_function

        if self.shuffle:
            np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.x_data) / self.batch_size))

    def __getitem__(self, index):
        start_idx = index * self.batch_size
        end_idx = (index + 1) * self.batch_size
        batch_indices = self.indices[start_idx:end_idx]
        #print(self.x_data.shape)
        batch_x = self.x_data[batch_indices]
        #print(batch_x.shape)
        batch_y = self.y_data[batch_indices]

        if self.preprocess_function is not None:
          batch_x = self.preprocess_function(batch_x)
          batch_y = self.preprocess_function(batch_y)

        # You can add any preprocessing steps here
        #print(batch_x.shape)
        return batch_x, batch_y

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

batch_size = 16

data_generator = ESPDataGenerator(x_train, y_train, batch_size)
data_generator_val = ESPDataGenerator(x_val, y_val, batch_size)

epochs = 2

for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        # Train your model using the current batch
        pass

In [25]:
len(x_train[0])

289

In [26]:
for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        print(batch_x)

Streaming output truncated to the last 5000 lines.
   -0.51452308]
  [ 1.09037149  0.60182306  0.60063221 ... -0.56487494  0.50495559
   -0.49122945]
  [ 1.1026179   0.60245745  0.60557644 ... -0.58497116  0.49968021
   -0.49122945]
  ...
  [ 1.09146006  0.60245745  0.60557644 ... -0.41616288  0.49968021
   -0.49122945]
  [ 1.08411221  0.60245745  0.60310433 ... -0.47645155  0.49704253
   -0.49122945]
  [ 1.06860009  0.60245745  0.60310433 ... -0.46439382  0.49968021
   -0.49122945]]

 [[-1.21875698 -1.53919792  0.38803009 ... -0.94268393  0.49968021
   -0.44464221]
  [-1.21875698 -1.53919792  0.38803009 ... -0.9667994   0.50495559
   -0.44464221]
  [-1.21875698 -1.53919792  0.38803009 ... -0.9667994   0.50495559
   -0.44464221]
  ...
  [-0.61242366 -1.53919792  0.38061374 ... -0.12275802  0.49968021
   -0.46793583]
  [-0.60099368 -1.53920982  0.3756695  ... -0.14687349  0.50759328
   -0.46793583]
  [-0.61977151 -1.53920585  0.3756695  ... -0.14687349  0.50759328
   -0.46793583]]

 ...

In [27]:
for x_batch, y_batch in data_generator:
  print(x_batch)
  print(x_batch.shape)

Streaming output truncated to the last 5000 lines.
  [-1.54750503 -1.69779501 -1.98767498 ... -1.05924203 -2.10899262
    1.97789454]
  [-1.54750503 -1.69779501 -1.98767498 ... -1.05924203 -2.21977549
    1.97789454]
  ...
  [-1.54750503 -1.69779501 -1.98767498 ... -1.05924203 -2.08525343
    1.97789454]
  [-1.54750503 -1.69779501 -1.98767498 ... -1.05924203 -2.25406543
    1.97789454]
  [-1.54750503 -1.69779501 -1.98767498 ... -1.05924203 -2.0509635
    1.97789454]]]
(16, 289, 8)
[[[-0.23387355  0.60210061  0.48444268 ...  0.64089846  0.49968021
   -0.51452308]
  [-0.23468998  0.60202131  0.48444268 ...  0.59266753  0.49968021
   -0.51452308]
  [-0.22951927  0.60202131  0.48444268 ...  0.16260835  0.49968021
   -0.51452308]
  ...
  [-0.2393164   0.60210061  0.48444268 ...  0.24701249  0.49176715
   -0.51452308]
  [-0.2374114   0.60202131  0.48444268 ...  0.59266753  0.49440484
   -0.51452308]
  [-0.24203782  0.60210061  0.4869148  ...  0.22289702  0.49704253
   -0.51452308]]

 [[ 1.13

In [28]:
loaded_data2[0]

NameError: ignored

In [ ]:
# for i in range(len(train_set)):
#   if len(train_set[i][0]) != 289:
#     print(len(train[i][0]))

In [ ]:
len(loaded_data)

In [ ]:
len(loaded_data[0][0])

In [ ]:
# import numpy as np

# shape = (len(loaded_data), len(loaded_data[0][0]), len(loaded_data[0][0][0]))
# data_array = np.zeros(shape)

# for i in range(len(loaded_data)):
#   data = loaded_data[i][0]

#   if len(data) != 289:
#     print(len(data))
#   #data_array[i] = data

In [ ]:

# def convert_to_numpy(obj):
#     if isinstance(obj, list):
#         return np.array([convert_to_numpy(item) for item in obj])
#     else:
#         return obj

# #converted_data = convert_to_numpy(loaded_data)

In [ ]:
#loaded_data = converted_data

In [ ]:
# import datetime

# def remove_datetime_objects(lst):
#     if isinstance(lst, list):
#         # Iterate through the list in reverse order to avoid index issues during removal
#         for i in range(len(lst) - 1, -1, -1):
#             if isinstance(lst[i], datetime.datetime):
#                 lst.pop(i)
#             else:
#                 remove_datetime_objects(lst[i])


# remove_datetime_objects(loaded_data)

In [ ]:
loaded_data[0]

In [ ]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
# train_num = round(len(loaded_data)*0.7)
# val_num = round(len(loaded_data)*0.1)
# test_num = round(len(loaded_data)*0.2)

# train_set = loaded_data[0:train_num]
# val_set = loaded_data[train_num:train_num + val_num]
# test_set = loaded_data[train_num + val_num:]

# #train_set = train_set

# # Split data into batches
# batch_size = train_num
# num_batches = train_num // batch_size
# num_features = 8

# # # Create an LSTM model
# # model = Sequential()
# # model.add(LSTM(units=64, activation='relu', input_shape=(len(loaded_data[0][0]), num_features)))
# # model.add(Dense(units=len(loaded_data[0][1]) * num_features))  # Output layer
# # model.compile(optimizer='adam', loss='mean_squared_error')

# # Define a custom data generator



In [ ]:
#train_set.ndim

In [ ]:
#converted_data = np.vectorize(lambda x: float(x.replace(',', '')))(ver_stack)


In [ ]:
# # Sample numpy array with empty arrays
# arr = np.array([[], [1, 2], [], [3, 4, 5], []])

# # Find indices of empty arrays
# empty_indices = np.where([len(sub_arr) == 0 for sub_arr in arr])[0]

# # Remove empty arrays
# arr = np.delete(arr, empty_indices, axis=0)

In [ ]:
# # Split data into batches
# batch_size = 32
# num_batches = len(train_set) // batch_size

# def data_generator(data_list, batch_size):
#     while True:
#         #for i in range(len(data_list)):
#         for batch in range(num_batches):
#             start_idx = batch * batch_size
#             end_idx = (batch + 1) * batch_size
#             batch_data = data_list[start_idx:end_idx]

#             x_batch = [inner[0] for inner in batch_data]
#             x_batch = scaler.fit_transform(x_batch)
#             x_batch = convert_to_numpy(x_batch)

#             y_batch = [inner[1] for inner in batch_data]
#             y_batch = scaler.fit_transform(y_batch)
#             y_batch = convert_to_numpy(y_batch)

#             yield x_batch, y_batch

In [ ]:
# def data_generator(data_list, batch_size):
#     #while True:
#   for i in range(len(data_list)):
#       x_batch = data_list[i][0]
#       #x_batch = scaler.fit_transform(x_batch)
#       x_batch = scaler.transform(x_batch)
#       x_batch = convert_to_numpy(x_batch)
#       x_batch = x_batch.reshape(1, len(data_list[i][0]), 8)
#       #empty_indices_x = np.where([len(sub_arr) == 0 for sub_arr in x_batch])[0]
#       #x_batch = np.delete(x_batch, empty_indices_x, axis
#       y_batch = data_list[i][1]
#       #y_batch = scaler.fit_transform(y_batch)
#       y_batch = scaler.transform(y_batch)
#       y_batch = convert_to_numpy(y_batch)
#       y_batch = y_batch.reshape(1, len(data_list[i][1]),8)
#       #empty_indices_y = np.where([len(sub_arr) == 0 for sub_arr in y_batch])[0]
#       #y_batch = np.delete(y_batch, empty_indices_y, axis

#       yield x_batch, y_batch

In [ ]:
# train_gen = data_generator(train_set, 1)
# val_gen = data_generator(val_set, 1)

In [ ]:
# x_train = [item[0] for item in train_set]
# y_train = [item[1] for item in train_set]

In [ ]:
type(x_train)

In [ ]:
len(x_train[0])

In [ ]:
import numpy as np

# Example nested list structure


# Check shapes of sublists and sub-sublists
shapes = set()
for sublist in x_train:
    for sub_sublist in sublist:
        shapes.add(len(sub_sublist))
        if len(sub_sublist) == 7:
          print(sub_sublist)

if len(shapes) > 1:
    print("Sub-sublists have different lengths, cannot convert to NumPy array")
else:
    x_train = np.array(x_train)

#print(x_train_array)


In [ ]:
print(shapes)

In [ ]:
#x_train = np.array(x_train)
y_train = np.array(y_train)


In [ ]:
x_train = x_train.reshape(len(x_train), len(x_train[0]),8)
y_train = y_train.reshape(len(y_train), len(y_train[0]),8)


In [ ]:
len(x_train[0])

In [ ]:
len(train_set[100][0])

In [ ]:
for i in range(len(train_set)):
  if len(x_train[i]) != 289:
    print("X mismatch: ", len(train_set[i]), i)
  elif len(y_train[i]) != 145:
    print("Y mismatch: ", len(train_set[i]), i)


In [ ]:
len(val_set)

In [ ]:
aa = next(train_gen)

In [ ]:
type(aa[0])

In [ ]:
aa[0].shape

In [ ]:
g = data_generator(train_set, 1)
for value in g:
  if value[0].shape != (1, 289, 8):
    print(value[0].shape)
  if value[1].shape != (1, 145, 8):
    print(value[1].shape)

In [ ]:
  # x_train = [sublist[0] for sublist in train_set]
  # x_val = [sublist[0] for sublist in val_set]

In [ ]:
# y_train = [sublist[1] for sublist in train_set]
# y_val = [sublist[1] for sublist in val_set]

In [ ]:
type(x_train[0])

In [ ]:
# def convert_to_numpy(data):
#     if isinstance(data, list):
#         return np.array([convert_to_numpy(item) for item in data])
#     else:
#         return data

# y_val = convert_to_numpy(y_val)

In [ ]:
type(y_val[0])

In [ ]:
# multivariate multi-step encoder-decoder lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

In [ ]:
x_train.ndim

In [ ]:
x_sample, y_sample = next(train_gen)
type(y_sample)

In [29]:
x_sample

NameError: ignored

In [ ]:
y_sample.ndim

In [30]:
x_train[0]

array([[ 0.2135286 ,  0.60245745,  0.57838315, ..., -0.23931612,
         0.51814403, -0.51452308],
       [ 0.21325645,  0.6022592 ,  0.57838315, ..., -0.32372026,
         0.49440484, -0.51452308],
       [ 0.2135286 ,  0.60217991,  0.57838315, ..., -0.28352781,
         0.50759328, -0.51452308],
       ...,
       [ 0.21053503,  0.6024178 ,  0.57838315, ..., -0.42018213,
         0.49968021, -0.51452308],
       [ 0.21053503,  0.60206096,  0.57838315, ..., -0.33979724,
         0.51023096, -0.51452308],
       [ 0.21053503,  0.60198166,  0.57838315, ..., -0.35587421,
         0.50759328, -0.51452308]])

In [31]:
# # x_train = scaler.fit_transform(x_train)
# # y_train = scaler.fit_transform(y_train)

# # TODO

# # Assuming x_train and y_train have shapes (num_samples, num_time_steps, num_features)
# # Reshape to (num_samples * num_time_steps, num_features)
# x_train = x_train.reshape(-1, num_features)
# y_train = y_train.reshape(-1, num_features)

# # Initialize the StandardScaler

# # Fit and transform the scaler on the reshaped data
# x_train = scaler.fit_transform(x_train)
# y_train = scaler.fit_transform(y_train)

# # Reshape the scaled data back to their original shapes if needed
# x_train = x_train.reshape(1, 288, num_features)
# y_train = y_train.reshape(1, 144, num_features)


NameError: ignored

In [33]:
import numpy as np
from keras.callbacks import Callback

class NMSECallback(Callback):
    def __init__(self, x_val, y_val):
        self.x_val = x_val
        self.y_val = y_val

    def on_epoch_end(self, epoch, logs=None):
        predictions = self.model.predict(self.x_val)
        mse = np.mean(np.square(predictions - self.y_val))
        true_variance = np.var(self.y_val)
        nmse = mse / true_variance
        print(f'\nEpoch {epoch + 1} - NMSE: {nmse:.4f}')

# Create the NMSE callback
nmse_callback = NMSECallback(x_val, y_val)

In [34]:
# Build the LSTM model
from keras.models import Sequential
from keras.layers import LSTM, Dense, RepeatVector, TimeDistributed
from tensorflow.keras.layers import Reshape
from keras.optimizers import Adam

#lr = 0.1  # Adjust this value as needed
#optimizer = Adam(learning_rate=lr)

model = Sequential()
#model.add(Reshape((num_features, 1), input_shape=(num_features,)))
#model.add(LSTM(50, input_shape=(len(train_set[0][0]), num_features), activation='relu'))
model.add(LSTM(50, activation='tanh'))
model.add(RepeatVector(145))
model.add(LSTM(50, return_sequences=True, activation='tanh'))
model.add(TimeDistributed(Dense(8)))  # Predict all 8 features for each step in the sequence
model.compile(optimizer='adam', loss='mse')


# Train the model
#history = model.fit(train_gen, epochs=1, validation_data=val_gen)
history = model.fit(data_generator, epochs=1, batch_size=16, validation_data=(x_val, y_val), callbacks=[nmse_callback])

16/16 [==============================] - 2s 57ms/step

Epoch 1 - NMSE: 0.0282
219/219 [==============================] - 58s 244ms/step - loss: 0.0801 - val_loss: 0.0261


In [ ]:
print(history.history['val_loss'])

[0.02276320941746235]


In [35]:
def calculate_nmse(y_true, y_pred):
    mse = np.mean(np.square(y_pred - y_true))
    true_variance = np.var(y_true)
    nmse = mse / true_variance
    return nmse

# Evaluate the model and calculate NMSE
predictions = model.predict(x_test)
nmse = calculate_nmse(y_test, predictions)

print("Normalized Mean Squared Error on Test Data:", nmse)

32/32 [==============================] - 3s 85ms/step
Normalized Mean Squared Error on Test Data: 0.015806617981136067


In [37]:
from sklearn.metrics import mean_absolute_error

# Reshape y_test and predictions
num_samples, num_steps, num_features = y_test.shape
y_test_reshaped = y_test.reshape(num_samples * num_steps, num_features)
predictions_reshaped = predictions.reshape(num_samples * num_steps, num_features)

# Calculate Mean Absolute Error
mae = mean_absolute_error(y_test_reshaped, predictions_reshaped)
print("Mean Absolute Error on Test Data:", mae)


Mean Absolute Error on Test Data: 0.06314588573395387


In [ ]:
print(type(x_train), x_train.shape)
print(type(y_train), y_train.shape)


In [ ]:
if np.isnan(x_train).any() or np.isnan(y_train).any():
    print("There are NaN values in the dataset.")

if np.isinf(x_train).any() or np.isinf(y_train).any():
    print("There are Inf values in the dataset.")

TypeError: ignored

In [ ]:
x_train.shape

(15091, 289, 8)

In [ ]:
y_train.shape

(15091, 145, 8)