<a href="https://colab.research.google.com/github/mbrz97/ESP/blob/main/naft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import joblib
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
file_path = '/content/drive/MyDrive/datalast.joblib'

In [4]:
loaded_data = joblib.load(file_path)

In [5]:
import datetime
def remove_datetime_from_nested_list(nested_list):
    if isinstance(nested_list, list):
        return [remove_datetime_from_nested_list(item) for item in nested_list if not isinstance(item, datetime.datetime)]
    else:
        return nested_list

loaded_data = remove_datetime_from_nested_list(loaded_data)

In [6]:
x_data = [item[0] for item in loaded_data[0:5000]]
y_data = [item[1] for item in loaded_data[0:5000]]

In [7]:
import numpy as np
x_data = np.array(x_data)
y_data = np.array(y_data)

In [8]:
del loaded_data

In [9]:
def convert_strings_to_floats(data):
    if isinstance(data, list):
        return [convert_strings_to_floats(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([convert_strings_to_floats(item) for item in data])
    elif isinstance(data, str):
        try:
            return float(data)
        except ValueError:
            return data
    else:
        return data


x_data = convert_strings_to_floats(x_data)
y_data = convert_strings_to_floats(y_data)

In [10]:
def remove_commas(data):
    if isinstance(data, list):
        return [remove_commas(item) for item in data]
    elif isinstance(data, np.ndarray):
        return np.array([remove_commas(item) for item in data])
    elif isinstance(data, str):
        return data.replace(',', '')
    else:
        return data

x_data = remove_commas(x_data)
y_data = remove_commas(y_data)

In [11]:
x_data.shape

(5000, 289, 8)

In [12]:
# Iterate through the array and convert strings to floats
for row in range(len(x_data)):
    for col in range(len(x_data[row])):
        element = x_data[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            x_data[row][col] = float(element.replace(",", ""))


# Iterate through the array and convert strings to floats
for row in range(len(y_data)):
    for col in range(len(y_data[row])):
        element = y_data[row][col]
        if isinstance(element, str):
            # Remove commas and convert to float
            y_data[row][col] = float(element.replace(",", ""))



In [16]:
from keras.utils import Sequence

class ESPDataGenerator(Sequence):
    def __init__(self, x_data, y_data, batch_size, shuffle=True, preprocess_function = None):
        self.x_data = x_data
        self.y_data = y_data
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indices = np.arange(len(self.x_data))
        self.preprocess_function = preprocess_function

        if self.shuffle:
            np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.ceil(len(self.x_data) / self.batch_size))

    def __getitem__(self, index):
        start_idx = index * self.batch_size
        end_idx = (index + 1) * self.batch_size
        batch_indices = self.indices[start_idx:end_idx]
        #print(self.x_data.shape)
        batch_x = self.x_data[batch_indices]
        print(batch_x.shape)
        batch_y = self.y_data[batch_indices]

        if self.preprocess_function is not None:
          batch_x = self.preprocess_function(batch_x)
        # You can add any preprocessing steps here

        return batch_x, batch_y

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

# Example usage
train_num = round(len(x_data)*0.7)
val_num = round(len(x_data)*0.1)
test_num = round(len(x_data)*0.2)

x_train = x_data[0:train_num]
x_val = x_data[train_num:train_num + val_num]
x_test = x_data[train_num + val_num:]

train_num_y = round(len(y_data)*0.7)
val_num_y = round(len(y_data)*0.1)
test_num_y = round(len(y_data)*0.2)

y_train = y_data[0:train_num]
y_val = y_data[train_num:train_num + val_num]
y_test = y_data[train_num + val_num:]

batch_size = 16

data_generator = ESPDataGenerator(x_train, y_train, batch_size)
data_generator_val = ESPDataGenerator(x_val, y_val, batch_size)

epochs = 2

for epoch in range(epochs):
    for batch_x, batch_y in data_generator:
        # Train your model using the current batch
        pass

(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
(16, 289, 8)

In [17]:
len(x_train[0])

289

In [18]:
for x_batch, y_batch in data_generator:
  print(x_batch)
  print(x_batch.shape)

Streaming output truncated to the last 5000 lines.
  [7.4720e+02 5.8010e+03 1.0380e+02 ... 3.2600e-01 1.2230e+02 9.8000e+00]]]
(16, 289, 8)
(16, 289, 8)
[[[1.7970e+03 5.8015e+03 6.8800e+01 ... 2.3000e-02 1.2070e+02 9.7000e+00]
  [1.7971e+03 5.8015e+03 6.8800e+01 ... 1.7000e-02 1.2070e+02 9.7000e+00]
  [1.7971e+03 5.8015e+03 6.8800e+01 ... 2.0000e-02 1.2070e+02 9.7000e+00]
  ...
  [1.7974e+03 5.8015e+03 6.8800e+01 ... 2.3000e-02 1.2080e+02 9.7000e+00]
  [1.7974e+03 5.8015e+03 6.8800e+01 ... 2.0000e-02 1.2070e+02 9.7000e+00]
  [1.7975e+03 5.8015e+03 6.8800e+01 ... 1.7000e-02 1.2070e+02 9.7000e+00]]

 [[9.6290e+02 5.8015e+03 1.0480e+02 ... 1.4400e-01 1.2190e+02 9.8000e+00]
  [9.6110e+02 5.8011e+03 1.0480e+02 ... 1.8100e-01 1.2220e+02 9.9000e+00]
  [9.6170e+02 5.8015e+03 1.0490e+02 ... 1.3500e-01 1.2180e+02 9.9000e+00]
  ...
  [9.6000e+02 5.8012e+03 1.0500e+02 ... 1.8900e-01 1.2220e+02 9.9000e+00]
  [9.5820e+02 5.8015e+03 1.0500e+02 ... 1.4500e-01 1.2190e+02 9.9000e+00]
  [9.6700e+02 5.800

In [ ]:
loaded_data2[0]

[[[datetime.datetime(2015, 1, 17, 14, 33),
   647.1,
   5801.5,
   103.8,
   117.4,
   0.52,
   0.204,
   122.7,
   9.8],
  [datetime.datetime(2015, 1, 17, 14, 43),
   647,
   5801,
   103.8,
   117.2,
   0.581,
   0.183,
   121.8,
   9.8],
  [datetime.datetime(2015, 1, 17, 14, 53),
   647.1,
   5800.8,
   103.8,
   117.3,
   0.517,
   0.193,
   122.3,
   9.8],
  [datetime.datetime(2015, 1, 17, 15, 3),
   648,
   5801.5,
   103.8,
   117.3,
   0.44,
   0.172,
   122,
   9.8],
  [datetime.datetime(2015, 1, 17, 15, 13),
   647.8,
   5800.4,
   103.8,
   117.2,
   0.646,
   0.169,
   122.4,
   9.8],
  [datetime.datetime(2015, 1, 17, 15, 23),
   647.3,
   5800.3,
   103.8,
   117.2,
   0.611,
   0.206,
   122,
   9.8],
  [datetime.datetime(2015, 1, 17, 15, 33),
   647,
   5801.3,
   103.8,
   117.2,
   0.494,
   0.205,
   122.4,
   9.8],
  [datetime.datetime(2015, 1, 17, 15, 43),
   646.8,
   5801.2,
   103.8,
   117.3,
   0.517,
   0.233,
   122,
   9.8],
  [datetime.datetime(2015, 1, 17,

In [ ]:
# for i in range(len(train_set)):
#   if len(train_set[i][0]) != 289:
#     print(len(train[i][0]))

In [ ]:
len(loaded_data)

21559

In [ ]:
len(loaded_data[0][0])

289

In [ ]:
# import numpy as np

# shape = (len(loaded_data), len(loaded_data[0][0]), len(loaded_data[0][0][0]))
# data_array = np.zeros(shape)

# for i in range(len(loaded_data)):
#   data = loaded_data[i][0]

#   if len(data) != 289:
#     print(len(data))
#   #data_array[i] = data

In [ ]:

# def convert_to_numpy(obj):
#     if isinstance(obj, list):
#         return np.array([convert_to_numpy(item) for item in obj])
#     else:
#         return obj

# #converted_data = convert_to_numpy(loaded_data)

In [ ]:
#loaded_data = converted_data

In [ ]:
# import datetime

# def remove_datetime_objects(lst):
#     if isinstance(lst, list):
#         # Iterate through the list in reverse order to avoid index issues during removal
#         for i in range(len(lst) - 1, -1, -1):
#             if isinstance(lst[i], datetime.datetime):
#                 lst.pop(i)
#             else:
#                 remove_datetime_objects(lst[i])


# remove_datetime_objects(loaded_data)

In [ ]:
loaded_data[0]

In [19]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
# train_num = round(len(loaded_data)*0.7)
# val_num = round(len(loaded_data)*0.1)
# test_num = round(len(loaded_data)*0.2)

# train_set = loaded_data[0:train_num]
# val_set = loaded_data[train_num:train_num + val_num]
# test_set = loaded_data[train_num + val_num:]

# #train_set = train_set

# # Split data into batches
# batch_size = train_num
# num_batches = train_num // batch_size
# num_features = 8

# # # Create an LSTM model
# # model = Sequential()
# # model.add(LSTM(units=64, activation='relu', input_shape=(len(loaded_data[0][0]), num_features)))
# # model.add(Dense(units=len(loaded_data[0][1]) * num_features))  # Output layer
# # model.compile(optimizer='adam', loss='mean_squared_error')

# # Define a custom data generator



In [ ]:
#train_set.ndim

AttributeError: ignored

In [ ]:
#vertical_stack = np.vstack(train_set)
ver_stack = np.empty((0, 8))
j = 0
for i in range(0, len(train_set), 1000):
  for item in train_set[i][0]:
    j += 1
    #temp = train_set[i]
    print(100*100*j/(len(train_set)*289))
    ver_stack = np.vstack((ver_stack, item))

0.002292894846237325
0.00458578969247465
0.0068786845387119756
0.0091715793849493
0.011464474231186626
0.013757369077423951
0.016050263923661275
0.0183431587698986
0.020636053616135925
0.022928948462373252
0.025221843308610575
0.027514738154847902
0.029807633001085226
0.03210052784732255
0.034393422693559876
0.0366863175397972
0.03897921238603453
0.04127210723227185
0.04356500207850918
0.045857896924746504
0.04815079177098383
0.05044368661722115
0.05273658146345848
0.055029476309695805
0.05732237115593313
0.05961526600217045
0.06190816084840778
0.0642010556946451
0.06649395054088243
0.06878684538711975
0.07107974023335709
0.0733726350795944
0.07566552992583173
0.07795842477206906
0.08025131961830638
0.0825442144645437
0.08483710931078103
0.08713000415701835
0.08942289900325569
0.09171579384949301
0.09400868869573033
0.09630158354196766
0.09859447838820498
0.1008873732344423
0.10318026808067964
0.10547316292691696
0.10776605777315429
0.11005895261939161
0.11235184746562893
0.11464474231

In [ ]:
#converted_data = np.vectorize(lambda x: float(x.replace(',', '')))(ver_stack)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(ver_stack)


In [ ]:
# # Sample numpy array with empty arrays
# arr = np.array([[], [1, 2], [], [3, 4, 5], []])

# # Find indices of empty arrays
# empty_indices = np.where([len(sub_arr) == 0 for sub_arr in arr])[0]

# # Remove empty arrays
# arr = np.delete(arr, empty_indices, axis=0)

In [ ]:
# # Split data into batches
# batch_size = 32
# num_batches = len(train_set) // batch_size

# def data_generator(data_list, batch_size):
#     while True:
#         #for i in range(len(data_list)):
#         for batch in range(num_batches):
#             start_idx = batch * batch_size
#             end_idx = (batch + 1) * batch_size
#             batch_data = data_list[start_idx:end_idx]

#             x_batch = [inner[0] for inner in batch_data]
#             x_batch = scaler.fit_transform(x_batch)
#             x_batch = convert_to_numpy(x_batch)

#             y_batch = [inner[1] for inner in batch_data]
#             y_batch = scaler.fit_transform(y_batch)
#             y_batch = convert_to_numpy(y_batch)

#             yield x_batch, y_batch

In [ ]:
def data_generator(data_list, batch_size):
    #while True:
  for i in range(len(data_list)):
      x_batch = data_list[i][0]
      #x_batch = scaler.fit_transform(x_batch)
      x_batch = scaler.transform(x_batch)
      x_batch = convert_to_numpy(x_batch)
      x_batch = x_batch.reshape(1, len(data_list[i][0]), 8)
      #empty_indices_x = np.where([len(sub_arr) == 0 for sub_arr in x_batch])[0]
      #x_batch = np.delete(x_batch, empty_indices_x, axis
      y_batch = data_list[i][1]
      #y_batch = scaler.fit_transform(y_batch)
      y_batch = scaler.transform(y_batch)
      y_batch = convert_to_numpy(y_batch)
      y_batch = y_batch.reshape(1, len(data_list[i][1]),8)
      #empty_indices_y = np.where([len(sub_arr) == 0 for sub_arr in y_batch])[0]
      #y_batch = np.delete(y_batch, empty_indices_y, axis

      yield x_batch, y_batch

In [ ]:
train_gen = data_generator(train_set, 1)
val_gen = data_generator(val_set, 1)

NameError: ignored

In [ ]:
len(train_set[0])

2

In [ ]:
len(train_set[0])


2

In [ ]:
x_train = [item[0] for item in train_set]
y_train = [item[1] for item in train_set]

In [ ]:
type(x_train)

list

In [ ]:
len(x_train[0])

289

In [ ]:
import numpy as np

# Example nested list structure


# Check shapes of sublists and sub-sublists
shapes = set()
for sublist in x_train:
    for sub_sublist in sublist:
        shapes.add(len(sub_sublist))
        if len(sub_sublist) == 7:
          print(sub_sublist)

if len(shapes) > 1:
    print("Sub-sublists have different lengths, cannot convert to NumPy array")
else:
    x_train = np.array(x_train)

#print(x_train_array)


In [ ]:
print(shapes)

{8}


In [ ]:
#x_train = np.array(x_train)
y_train = np.array(y_train)


In [ ]:
x_train = x_train.reshape(len(x_train), len(x_train[0]),8)
y_train = y_train.reshape(len(y_train), len(y_train[0]),8)


In [ ]:
len(x_train[0])

289

In [ ]:
len(train_set[100][0])

289

In [ ]:
for i in range(len(train_set)):
  if len(x_train[i]) != 289:
    print("X mismatch: ", len(train_set[i]), i)
  elif len(y_train[i]) != 145:
    print("Y mismatch: ", len(train_set[i]), i)


In [ ]:
len(val_set)

2207

In [ ]:
aa = next(train_gen)

StopIteration: ignored

In [ ]:
type(aa[0])

numpy.ndarray

In [ ]:
aa[0].shape

(1, 289, 8)

In [ ]:
g = data_generator(train_set, 1)
for value in g:
  if value[0].shape != (1, 289, 8):
    print(value[0].shape)
  if value[1].shape != (1, 145, 8):
    print(value[1].shape)

ValueError: ignored

In [ ]:
  # x_train = [sublist[0] for sublist in train_set]
  # x_val = [sublist[0] for sublist in val_set]

In [ ]:
# y_train = [sublist[1] for sublist in train_set]
# y_val = [sublist[1] for sublist in val_set]

In [ ]:
type(x_train[0])

NameError: ignored

In [ ]:
# def convert_to_numpy(data):
#     if isinstance(data, list):
#         return np.array([convert_to_numpy(item) for item in data])
#     else:
#         return data

# y_val = convert_to_numpy(y_val)

In [ ]:
type(y_val[0])

NameError: ignored

In [ ]:
# multivariate multi-step encoder-decoder lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

In [ ]:
x_train.ndim

NameError: ignored

In [ ]:
x_sample, y_sample = next(train_gen)
type(y_sample)

numpy.ndarray

In [ ]:
x_sample

array([[ 1.29375408e+00, -1.89048300e+00,  4.83169060e-13, ...,
        -3.95046716e-01, -5.68631379e-02, -2.66453526e-14],
       [ 1.44253838e+00,  4.30089662e-02,  4.83169060e-13, ...,
        -1.33200610e+00,  2.71805799e-01, -2.66453526e-14],
       [ 2.33524414e+00,  8.71648382e-01,  4.83169060e-13, ...,
         2.60824853e-01, -1.04286995e+00, -2.66453526e-14],
       ...,
       [-1.53314750e+00,  8.71648382e-01,  4.83169060e-13, ...,
        -2.02629625e-02,  9.29143674e-01, -2.66453526e-14],
       [-6.40441735e-01,  5.95435244e-01,  4.83169060e-13, ...,
        -3.95046716e-01,  9.29143674e-01, -2.66453526e-14],
       [ 1.03479734e-01, -1.06184359e+00,  4.83169060e-13, ...,
         2.60824853e-01,  2.71805799e-01, -2.66453526e-14]])

In [ ]:
y_sample.ndim

2

In [ ]:
x_train[0]

array([-0.10032837,  1.54959423,  0.72483291,  0.65543456,  0.06481088,
        0.2254971 ,  0.43033047, -0.4539014 ])

In [ ]:
# x_train = scaler.fit_transform(x_train)
# y_train = scaler.fit_transform(y_train)

# TODO

# Assuming x_train and y_train have shapes (num_samples, num_time_steps, num_features)
# Reshape to (num_samples * num_time_steps, num_features)
x_train = x_train.reshape(-1, num_features)
y_train = y_train.reshape(-1, num_features)

# Initialize the StandardScaler

# Fit and transform the scaler on the reshaped data
x_train = scaler.fit_transform(x_train)
y_train = scaler.fit_transform(y_train)

# Reshape the scaled data back to their original shapes if needed
x_train = x_train.reshape(1, 288, num_features)
y_train = y_train.reshape(1, 144, num_features)


NameError: ignored

In [ ]:
# Build the LSTM model
from keras.models import Sequential
from keras.layers import LSTM, Dense, RepeatVector, TimeDistributed
from tensorflow.keras.layers import Reshape
from keras.optimizers import Adam

lr = 0.001  # Adjust this value as needed
optimizer = Adam(learning_rate=lr)

model = Sequential()
#model.add(Reshape((num_features, 1), input_shape=(num_features,)))
#model.add(LSTM(50, input_shape=(len(train_set[0][0]), num_features), activation='relu'))
model.add(LSTM(5, activation='tanh'))
model.add(RepeatVector(145))
model.add(LSTM(5, return_sequences=True, activation='tanh'))
model.add(TimeDistributed(Dense(8)))  # Predict all 8 features for each step in the sequence
model.compile(optimizer='adam', loss='mse')


# Train the model
#history = model.fit(train_gen, epochs=1, validation_data=val_gen)
history = model.fit(data_generator, epochs=1, batch_size=16)

(16, 289, 8)
(16, 289, 8)
(16, 289, 8)
313/313 [==============================] - 59s 169ms/step - loss: 1897161.1250


In [ ]:
print(type(x_train), x_train.shape)
print(type(y_train), y_train.shape)


In [ ]:
if np.isnan(x_train).any() or np.isnan(y_train).any():
    print("There are NaN values in the dataset.")

if np.isinf(x_train).any() or np.isinf(y_train).any():
    print("There are Inf values in the dataset.")

TypeError: ignored

In [ ]:
x_train.shape

(15091, 289, 8)

In [ ]:
y_train.shape

(15091, 145, 8)